execute pathogen#infect()

"""""""""""""""""""""""""""""""""""""
" Local overrides                   "
"""""""""""""""""""""""""""""""""""""
source ~/.vimrc_local

syntax on
filetype plugin indent on
set nocompatible
set ruler
set mouse=a
set showmatch  " Show matching braces/brackets
set number  " Show line numbers
set expandtab  " Expand tabs into spaces
set tabstop=2   "show tabas as two spaces
set softtabstop=2 " Make tabs act like spaces for editing ops
set autoindent  "always have autoidenting on
set shiftwidth=2  "autoindent uses this space
set shiftround
set smarttab
set cursorline  "highlight current line
set winwidth=80
set wrap
set title       "let vim change tab/window title

" where to open splits
set splitbelow
set splitright

"""""""""""""""""""""""""""""""""""""
"search options                     "
"""""""""""""""""""""""""""""""""""""
set ignorecase smartcase "case insensitive only if they contain upper-case characters
set incsearch   "incremental search
" Use <C-L> to clear the highlighting of :set hlsearch.
if maparg('<C-L>', 'n') ==# ''
  nnoremap <silent> <C-L> :nohlsearch<CR><C-L>
endif
set hls         "highlight results

" status line
set statusline=2
:set statusline=%<%f\ (%{&ft})\ %-4(%m%)%=%-19(%3l,%02c%03V%)


"""""""""""""""""""""""""""""""""""""
" Custom bindings                   "
"""""""""""""""""""""""""""""""""""""
" Lets you ctrl+hjkl to move between splits
map <C-k> <C-w><Up>
map <C-j> <C-w><Down>
map <C-l> <C-w><Right>
map <C-h> <C-w><Left>
" Fix typos
command! Q  quit
command! W  write
command! Wq wq
command! WQ wq
command! Qa qa
command! QA qa
command! Wqa wqa
command! WQa wqa
command! WQA wqa
map K gk

"show at least one line around cursor
if !&scrolloff
  set scrolloff=1
endif
if !&sidescrolloff
  set sidescrolloff=5
endif
set display+=lastline

" CtrlP Settings
set wildignore+=*/tmp/*,*.so,*.swp,*.zip     " MacOSX/Linux

" Set colors to grb256
set t_Co=256
colorscheme grb256
